### ISSUE TITLE
Image classifier: gather dataset

### ISSUE THREAD

**Issue by larafranciulli** [cmvan/cs152-spr24-group29#13]
We need to find a reasonable analogous dataset to train a classifier as working with CSAM content is illegal

**Comment by cmvan** [comment]
This repository aggregates images for NSFW image classifiers: [nsfw_data_scraper](https://github.com/alex000kim/nsfw_data_scraper)
Training to detect adult sexual content could be a good analogue to CSAM that is legal

**Comment by cmvan** [comment]
Used the Pan12 dataset to train NLP model for text classifier
